/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#fdf7ff",
        "on-surface-variant": "#566166",
        "on-surface": "#2a3439",
        "on-tertiary-container": "#4f4964",
        "surface-dim": "#cfdce3",
        "primary-fixed": "#dde1ff",
        "outline-variant": "#a9b4b9",
        "on-primary-fixed-variant": "#3352c0",
        "surface-bright": "#f7f9fb",
        "surface-container": "#e8eff3",
        "on-primary-fixed": "#0732a3",
        "on-tertiary-fixed": "#3c3650",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#752121",
        "error-dim": "#4e0309",
        "background": "#f7f9fb",
        "surface": "#f7f9fb",
        "tertiary-container": "#dfd5f7",
        "on-secondary": "#faf8fc",
        "secondary-container": "#e4e2e6",
        "secondary-fixed": "#e4e2e6",
        "on-primary-container": "#2747b6",
        "surface-container-highest": "#d9e4ea",
        "primary": "#3755c3",
        "tertiary": "#625b77",
        "primary-container": "#dde1ff",
        "primary-fixed-dim": "#cad2ff",
        "surface-tint": "#3755c3",
        "on-background": "#2a3439",
        "secondary-fixed-dim": "#d5d3d8",
        "error": "#9f403d",
        "primary-dim": "#2848b7",
        "tertiary-dim": "#564f6b",
        "on-secondary-fixed": "#3f3f43",
        "outline": "#717c82",
        "on-error": "#fff7f6",
        "error-container": "#fe8983",
        "secondary": "#5f5f62",
        "tertiary-fixed-dim": "#d0c7e8",
        "inverse-surface": "#0b0f10",
        "inverse-primary": "#6d89fa",
        "surface-container-low": "#f0f4f7",
        "inverse-on-surface": "#9a9d9f",
        "on-secondary-fixed-variant": "#5b5b5f",
        "on-secondary-container": "#515155",
        "secondary-dim": "#535356",
        "on-primary": "#f8f7ff",
        "surface-container-high": "#e1e9ee",
        "surface-variant": "#d9e4ea",
        "tertiary-fixed": "#dfd5f7",
        "on-tertiary-fixed-variant": "#59526e"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5xl",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
