export const FETCH_PRINCIPAL_DASHBOARD_REQUEST = 'FETCH_PRINCIPAL_DASHBOARD_REQUEST';
export const FETCH_PRINCIPAL_DASHBOARD_SUCCESS = 'FETCH_PRINCIPAL_DASHBOARD_SUCCESS';
export const FETCH_PRINCIPAL_DASHBOARD_FAILURE = 'FETCH_PRINCIPAL_DASHBOARD_FAILURE';

export const FETCH_STAFF_ATTENDANCE_GRAPH_REQUEST = 'FETCH_STAFF_ATTENDANCE_GRAPH_REQUEST';
export const FETCH_STAFF_ATTENDANCE_GRAPH_SUCCESS = 'FETCH_STAFF_ATTENDANCE_GRAPH_SUCCESS';
export const FETCH_STAFF_ATTENDANCE_GRAPH_FAILURE = 'FETCH_STAFF_ATTENDANCE_GRAPH_FAILURE';

export const SET_DASHBOARD_FILTER = 'SET_DASHBOARD_FILTER';

export const FETCH_YEARS_REQUEST = 'FETCH_YEARS_REQUEST';
export const FETCH_YEARS_SUCCESS = 'FETCH_YEARS_SUCCESS';
export const FETCH_YEARS_FAILURE = 'FETCH_YEARS_FAILURE';

export const FETCH_SECTIONS_REQUEST = 'FETCH_SECTIONS_REQUEST';
export const FETCH_SECTIONS_SUCCESS = 'FETCH_SECTIONS_SUCCESS';
export const FETCH_SECTIONS_FAILURE = 'FETCH_SECTIONS_FAILURE';
 
export const FETCH_ASSESSMENT_TYPES_REQUEST = 'FETCH_ASSESSMENT_TYPES_REQUEST';
export const FETCH_ASSESSMENT_TYPES_SUCCESS = 'FETCH_ASSESSMENT_TYPES_SUCCESS';
export const FETCH_ASSESSMENT_TYPES_FAILURE = 'FETCH_ASSESSMENT_TYPES_FAILURE';

export const FETCH_MARKS_DISTRIBUTION_REQUEST = 'FETCH_MARKS_DISTRIBUTION_REQUEST';
export const FETCH_MARKS_DISTRIBUTION_SUCCESS = 'FETCH_MARKS_DISTRIBUTION_SUCCESS';
export const FETCH_MARKS_DISTRIBUTION_FAILURE = 'FETCH_MARKS_DISTRIBUTION_FAILURE';

export const FETCH_ATTENDANCE_TRENDS_REQUEST = 'FETCH_ATTENDANCE_TRENDS_REQUEST';
export const FETCH_ATTENDANCE_TRENDS_SUCCESS = 'FETCH_ATTENDANCE_TRENDS_SUCCESS';
export const FETCH_ATTENDANCE_TRENDS_FAILURE = 'FETCH_ATTENDANCE_TRENDS_FAILURE';

export const FETCH_DEPARTMENT_AVERAGES_REQUEST = 'FETCH_DEPARTMENT_AVERAGES_REQUEST';
export const FETCH_DEPARTMENT_AVERAGES_SUCCESS = 'FETCH_DEPARTMENT_AVERAGES_SUCCESS';
export const FETCH_DEPARTMENT_AVERAGES_FAILURE = 'FETCH_DEPARTMENT_AVERAGES_FAILURE';


