export const FETCH_PRINCIPAL_DASHBOARD_REQUEST = 'FETCH_PRINCIPAL_DASHBOARD_REQUEST';
export const FETCH_PRINCIPAL_DASHBOARD_SUCCESS = 'FETCH_PRINCIPAL_DASHBOARD_SUCCESS';
export const FETCH_PRINCIPAL_DASHBOARD_FAILURE = 'FETCH_PRINCIPAL_DASHBOARD_FAILURE';

export const FETCH_STAFF_ATTENDANCE_GRAPH_REQUEST = 'FETCH_STAFF_ATTENDANCE_GRAPH_REQUEST';
export const FETCH_STAFF_ATTENDANCE_GRAPH_SUCCESS = 'FETCH_STAFF_ATTENDANCE_GRAPH_SUCCESS';
export const FETCH_STAFF_ATTENDANCE_GRAPH_FAILURE = 'FETCH_STAFF_ATTENDANCE_GRAPH_FAILURE';
