export const FETCH_PRINCIPAL_DASHBOARD_REQUEST = 'FETCH_PRINCIPAL_DASHBOARD_REQUEST';
export const FETCH_PRINCIPAL_DASHBOARD_SUCCESS = 'FETCH_PRINCIPAL_DASHBOARD_SUCCESS';
export const FETCH_PRINCIPAL_DASHBOARD_FAILURE = 'FETCH_PRINCIPAL_DASHBOARD_FAILURE';
