export const FETCH_GUARDIAN_DASHBOARD_REQUEST = 'FETCH_GUARDIAN_DASHBOARD_REQUEST';
export const FETCH_GUARDIAN_DASHBOARD_SUCCESS = 'FETCH_GUARDIAN_DASHBOARD_SUCCESS';
export const FETCH_GUARDIAN_DASHBOARD_FAILURE = 'FETCH_GUARDIAN_DASHBOARD_FAILURE';

export const FETCH_GUARDIAN_ATTENDANCE_REQUEST = 'FETCH_GUARDIAN_ATTENDANCE_REQUEST';
export const FETCH_GUARDIAN_ATTENDANCE_SUCCESS = 'FETCH_GUARDIAN_ATTENDANCE_SUCCESS';
export const FETCH_GUARDIAN_ATTENDANCE_FAILURE = 'FETCH_GUARDIAN_ATTENDANCE_FAILURE';

export const FETCH_GUARDIAN_FEES_REQUEST = 'FETCH_GUARDIAN_FEES_REQUEST';
export const FETCH_GUARDIAN_FEES_SUCCESS = 'FETCH_GUARDIAN_FEES_SUCCESS';
export const FETCH_GUARDIAN_FEES_FAILURE = 'FETCH_GUARDIAN_FEES_FAILURE';

export const SELECT_CHILD = 'SELECT_CHILD';
