export const GET_INSTITUTIONS_REQUEST = 'GET_INSTITUTIONS_REQUEST';
export const GET_INSTITUTIONS_SUCCESS = 'GET_INSTITUTIONS_SUCCESS';
export const GET_INSTITUTIONS_FAILURE = 'GET_INSTITUTIONS_FAILURE';
