export const FETCH_PAPER_MASTER_DATA_REQUEST = 'FETCH_PAPER_MASTER_DATA_REQUEST';
export const FETCH_PAPER_MASTER_DATA_SUCCESS = 'FETCH_PAPER_MASTER_DATA_SUCCESS';
export const FETCH_PAPER_MASTER_DATA_FAILURE = 'FETCH_PAPER_MASTER_DATA_FAILURE';

export const FETCH_PAPER_SUBMISSIONS_REQUEST = 'FETCH_PAPER_SUBMISSIONS_REQUEST';
export const FETCH_PAPER_SUBMISSIONS_SUCCESS = 'FETCH_PAPER_SUBMISSIONS_SUCCESS';
export const FETCH_PAPER_SUBMISSIONS_FAILURE = 'FETCH_PAPER_SUBMISSIONS_FAILURE';

export const SUBMIT_PAPER_GRADING_REQUEST = 'SUBMIT_PAPER_GRADING_REQUEST';
export const SUBMIT_PAPER_GRADING_SUCCESS = 'SUBMIT_PAPER_GRADING_SUCCESS';
export const SUBMIT_PAPER_GRADING_FAILURE = 'SUBMIT_PAPER_GRADING_FAILURE';
