// Action Types for Remarks
export const FETCH_REMARKS_SUMMARY_REQUEST = 'FETCH_REMARKS_SUMMARY_REQUEST';
export const FETCH_REMARKS_SUMMARY_SUCCESS = 'FETCH_REMARKS_SUMMARY_SUCCESS';
export const FETCH_REMARKS_SUMMARY_FAILURE = 'FETCH_REMARKS_SUMMARY_FAILURE';

export const FETCH_REMARKS_FEED_REQUEST = 'FETCH_REMARKS_FEED_REQUEST';
export const FETCH_REMARKS_FEED_SUCCESS = 'FETCH_REMARKS_FEED_SUCCESS';
export const FETCH_REMARKS_FEED_FAILURE = 'FETCH_REMARKS_FEED_FAILURE';

export const RESOLVE_REMARK_REQUEST = 'RESOLVE_REMARK_REQUEST';
export const RESOLVE_REMARK_SUCCESS = 'RESOLVE_REMARK_SUCCESS';
export const RESOLVE_REMARK_FAILURE = 'RESOLVE_REMARK_FAILURE';

export const SET_REMARKS_SCOPE = 'SET_REMARKS_SCOPE';
