export const FETCH_STUDENT_DASHBOARD_REQUEST = 'FETCH_STUDENT_DASHBOARD_REQUEST';
export const FETCH_STUDENT_DASHBOARD_SUCCESS = 'FETCH_STUDENT_DASHBOARD_SUCCESS';
export const FETCH_STUDENT_DASHBOARD_FAILURE = 'FETCH_STUDENT_DASHBOARD_FAILURE';

export const FETCH_STUDENT_PROFILE_REQUEST = 'FETCH_STUDENT_PROFILE_REQUEST';
export const FETCH_STUDENT_PROFILE_SUCCESS = 'FETCH_STUDENT_PROFILE_SUCCESS';
export const FETCH_STUDENT_PROFILE_FAILURE = 'FETCH_STUDENT_PROFILE_FAILURE';

export const FETCH_STUDENT_REMARKS_REQUEST = 'FETCH_STUDENT_REMARKS_REQUEST';
export const FETCH_STUDENT_REMARKS_SUCCESS = 'FETCH_STUDENT_REMARKS_SUCCESS';
export const FETCH_STUDENT_REMARKS_FAILURE = 'FETCH_STUDENT_REMARKS_FAILURE';

export const SET_STUDENT_DASHBOARD_SEMESTER = 'SET_STUDENT_DASHBOARD_SEMESTER';

export const SUBMIT_REMARK_REQUEST = 'SUBMIT_REMARK_REQUEST';
export const SUBMIT_REMARK_SUCCESS = 'SUBMIT_REMARK_SUCCESS';
export const SUBMIT_REMARK_FAILURE = 'SUBMIT_REMARK_FAILURE';

export const FETCH_STAFF_LIST_REQUEST = 'FETCH_STAFF_LIST_REQUEST';
export const FETCH_STAFF_LIST_SUCCESS = 'FETCH_STAFF_LIST_SUCCESS';
export const FETCH_STAFF_LIST_FAILURE = 'FETCH_STAFF_LIST_FAILURE';

export const FETCH_STUDENT_SUBMISSION_DETAILS_REQUEST = 'FETCH_STUDENT_SUBMISSION_DETAILS_REQUEST';
export const FETCH_STUDENT_SUBMISSION_DETAILS_SUCCESS = 'FETCH_STUDENT_SUBMISSION_DETAILS_SUCCESS';
export const FETCH_STUDENT_SUBMISSION_DETAILS_FAILURE = 'FETCH_STUDENT_SUBMISSION_DETAILS_FAILURE';

