export const FETCH_STUDENTS_REQUEST = 'FETCH_STUDENTS_REQUEST';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAILURE = 'FETCH_STUDENTS_FAILURE';

export const SET_STUDENT_FILTER = 'SET_STUDENT_FILTER';
export const SET_STUDENT_MULTIPLE_FILTERS = 'SET_STUDENT_MULTIPLE_FILTERS';
export const SET_STUDENT_SORT = 'SET_STUDENT_SORT';

export const SET_STUDENT_PAGE = 'SET_STUDENT_PAGE';
export const RESET_STUDENT_FILTERS = 'RESET_STUDENT_FILTERS';

export const FETCH_FILTERS_REQUEST = 'FETCH_FILTERS_REQUEST';
export const FETCH_FILTERS_SUCCESS = 'FETCH_FILTERS_SUCCESS';
export const FETCH_FILTERS_FAILURE = 'FETCH_FILTERS_FAILURE';

export const FETCH_TOP_PERFORMERS_REQUEST = 'FETCH_TOP_PERFORMERS_REQUEST';
export const FETCH_TOP_PERFORMERS_SUCCESS = 'FETCH_TOP_PERFORMERS_SUCCESS';
export const FETCH_TOP_PERFORMERS_FAILURE = 'FETCH_TOP_PERFORMERS_FAILURE';
