// Dashboard Summary
export const FETCH_TRANSPORT_DASHBOARD_REQUEST = 'FETCH_TRANSPORT_DASHBOARD_REQUEST';
export const FETCH_TRANSPORT_DASHBOARD_SUCCESS = 'FETCH_TRANSPORT_DASHBOARD_SUCCESS';
export const FETCH_TRANSPORT_DASHBOARD_FAILURE = 'FETCH_TRANSPORT_DASHBOARD_FAILURE';

// On-Duty Staff
export const FETCH_TRANSPORT_ON_DUTY_REQUEST = 'FETCH_TRANSPORT_ON_DUTY_REQUEST';
export const FETCH_TRANSPORT_ON_DUTY_SUCCESS = 'FETCH_TRANSPORT_ON_DUTY_SUCCESS';
export const FETCH_TRANSPORT_ON_DUTY_FAILURE = 'FETCH_TRANSPORT_ON_DUTY_FAILURE';

// All Staff
export const FETCH_TRANSPORT_STAFF_REQUEST = 'FETCH_TRANSPORT_STAFF_REQUEST';
export const FETCH_TRANSPORT_STAFF_SUCCESS = 'FETCH_TRANSPORT_STAFF_SUCCESS';
export const FETCH_TRANSPORT_STAFF_FAILURE = 'FETCH_TRANSPORT_STAFF_FAILURE';

// Toggle Staff Status
export const TOGGLE_STAFF_STATUS_REQUEST = 'TOGGLE_STAFF_STATUS_REQUEST';
export const TOGGLE_STAFF_STATUS_SUCCESS = 'TOGGLE_STAFF_STATUS_SUCCESS';
export const TOGGLE_STAFF_STATUS_FAILURE = 'TOGGLE_STAFF_STATUS_FAILURE';

// Routes
export const FETCH_TRANSPORT_ROUTES_REQUEST = 'FETCH_TRANSPORT_ROUTES_REQUEST';
export const FETCH_TRANSPORT_ROUTES_SUCCESS = 'FETCH_TRANSPORT_ROUTES_SUCCESS';
export const FETCH_TRANSPORT_ROUTES_FAILURE = 'FETCH_TRANSPORT_ROUTES_FAILURE';
