spring.application.name=edutrack

# MASTER DB (Writes)
spring.datasource.master.url=jdbc:mysql://localhost:3306/edutrack?createDatabaseIfNotExist=true
spring.datasource.master.username=root
spring.datasource.master.password=Start#123
spring.datasource.master.driver-class-name=com.mysql.cj.jdbc.Driver

# REPLICA DB (Reads)
spring.datasource.replica.url=jdbc:mysql://localhost:3307/edutrack?createDatabaseIfNotExist=true
spring.datasource.replica.username=root
spring.datasource.replica.password=Start#123
spring.datasource.replica.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

websiteUrl=http://localhost:3000/

# Hibernate Batching Optimization
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.batch_versioned_data=true